pipeline {
    agent any
    tools {
        nodejs 'NodeJS'
    }

    stages {
        stage("Install Dependencies") {
            steps {
                script {
                    echo "Installing dependencies..."
                    sh 'npm install' 
                }
            }
        }
        stage("Build") {
            steps {
                script {
                    echo "Building the application..."
                    sh 'npm run build' 
                }
            }
        }
    
        stage("Deploy") {
            steps {
                script {
                    echo "Deploying the application..."
                    sh 'nohup npm start &'

                }
            }
        }
    }

    post {
        always {
            script {
                echo "Cleaning workspace..."
                cleanWs()
            }
        }
    }
}
